# GitHub Pages settings; cannot be changed.
# lsi: false
# safe: true
# source: .
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge

# Serving
host: "0.0.0.0" # Probably should fix. Lets me host on local networks anyway.

# Content
show_drafts: false
exclude: [ # Jekyll 3 *replaces* the default; Jekyll 4 adds.
  ".sass-cache/",
  ".jekyll-cache/",
  "gemfiles/",
  "Gemfile",
  "Gemfile.lock",
  "vendor/",
  "Rakefile",
]
