permalink: "/writs/:title:output_ext"
sass:
  sass_dir: "assets/styles/_sass"
latest_posts_limit: 10
name: "rocx.rocks"
title_separator: " :: "
contacts:
  - name: "GitHub"
    title: "rocx"
    uri: "https://github.com/rocx"
  - name: "eMail"
    title: "rocx@rocx.rocks"
    uri: "mailto:rocx+pub1@rocx.rocks" # I'll *know* when it gets scraped.

show_drafts: true
future: true
strict_front_matter: true

port: 8080
host: "0.0.0.0"                 # To test via (W)LAN.
livereload: true
